drop_mapped_sources = """DROP TABLE IF EXISTS mapped_sources;"""

table_create_mapped_sources = """
CREATE TABLE `mapped_sources` (
  `id` int(11) DEFAULT NULL,
  `old_source_id` int(11) DEFAULT NULL,
  `old_source_name` text,
  `new_source_id` int(11) DEFAULT NULL,
  `new_source_name` text,
  `comments` text
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
"""


insert_mapped_sources = """
insert  into `mapped_sources`(`id`,`old_source_id`,`old_source_name`,`new_source_id`,`new_source_name`,`comments`) values 
(1,2,'GED',23,'General Economic Division (GED), Planning Commission, Ministry of Planning',''),
(2,5,'WB',113,'PovcalNet, WB',''),
(3,13,'Census',160,'Census wing, Bangladesh Bureau of Statistics, Statistics and Informatics Division, Ministry of Planning',''),
(4,15,'BPS',61,'Bangladesh Parliament Secretariat (BPS)',''),
(5,19,'UNAIDS',28,'UNAIDS',''),
(6,20,'NASP',27,'NASP, Directorate General of Health Services (DGHS), Health Services Division, Ministry of Health & Family Welfare',''),
(7,24,'WHO',36,'WHO','Need Clarification'),
(8,25,'WHO',196,'WHO, Bangladesh Bureau of Statistics','Need Clarification'),
(9,30,'IUCN',139,'IUCN, Forest Department, Ministry of Environment, Forest and Climate Change',''),
(10,31,'BNH',45,'BNHA, Health Economics Unit, Health Services Division, Ministry of Health & Family Welfare',''),
(11,33,'ERD',14,'Economic Relations Division, Ministry of Finance',''),
(12,37,' SID',30,'SDG cell, Statistics and Informatics Division, Ministry of Planning','Need Clarification'),
(13,45,'MoA',153,'Ministry of Agriculture',''),
(14,53,'MoST',88,'Ministry of Science and Technology',''),
(15,58,'MoC',83,'Ministry of Commerce',''),
(16,65,'MoDMR',5,'Ministry of Disaster Management and Relief',''),
(17,69,'LPAD',150,'Bangladesh National Human Rights Commission, Legislative and Parliamentary Affairs Division, Ministry of Law, Justice and Parliamentary Affairs',''),
(18,70,'MoWCA',56,'Ministry of Women and Children Affairs',''),
(19,80,'MoE',117,'Ministry of Education',''),
(20,83,'LGD',62,'Local Government Division, Ministry of Local Government, Rural Development and Co-operatives',''),
(21,85,'MoPA',147,'Ministry of Public Administration',''),
(22,88,'MoYS',84,'Ministry of Youth and Sports',''),
(23,90,'MoLE',46,'Ministry of Labour and Employment',''),
(24,111,'MoEWOE',81,'Ministry of Expatriatesâ€™ Welfare and Overseas Employment',''),
(25,122,'MOFA',95,'Ministry of Foreign Affairs',''),
(26,131,'MoCA',121,'Ministry of Cultural Affairs',''),
(27,143,'MoD',138,'Ministry of Defence',''),
(28,145,'MoEFCC',122,'Ministry of Environment, Forest and Climate Change',''),
(29,146,'MoEFCC->Bangladesh Forest Department (BFD)',24,'Forest Department, Ministry of Environment, Forest and Climate Change',''),
(30,151,' SID->BBS',136,'Bangladesh Bureau of Statistics, Statistics and Informatics Division, Ministry of Planning',''),
(31,152,'MoFL->DoF',72,'THE DEPARTMENT OF FISHERIES (DOF), Ministry of Fisheries And Livestock',''),
(32,153,' SID->BBS->NAW',11,'NAW, Bangladesh Bureau of Statistics, Statistics and Informatics Division, Ministry of Planning',''),
(33,154,'LJD',148,'Law and Justice Division, Ministry of Law, Justice and Parliamentary Affairs',''),
(34,155,'NHRC',150,'Bangladesh National Human Rights Commission, Legislative and Parliamentary Affairs Division, Ministry of Law, Justice and Parliamentary Affairs',''),
(35,157,'MoHA->BP',39,'Bangladesh Police, Public Security Division, Ministry of Home Affairs',''),
(36,164,' SID->BBS->HIES',1,'HIES, Bangladesh Bureau of Statistics, Statistics and Informatics Division, Ministry of Planning',''),
(37,171,'MoDMR->DDM',123,'Department of Disaster Management, Ministry of Disaster Management and Relief',''),
(38,172,' SID->BBS->BDRHS',4,'BDRHS, Bangladesh Bureau of Statistics, Statistics and Informatics Division, Ministry of Planning',''),
(39,173,'HSD->DGHS',50,'Health Services Division, Ministry of Health & Family Welfare',''),
(40,174,'HSD->DGHS->MIS',38,'MIS, Directorate General of Health Services (DGHS), Health Services Division, Ministry of Health & Family Welfare',''),
(41,179,' SID->BBS->MICS',2,'MICS, Bangladesh Bureau of Statistics, Statistics and Informatics Division, Ministry of Planning',''),
(42,185,'MoA->BARI',142,'Bangladesh Agricultural Research Institute (BARI), Ministry of Agriculture',''),
(43,186,'MoC->BTC',20,'Bangladesh Trade and Tariff Commission (BTTC), Ministry of Commerce',''),
(44,189,' SID->BBS->SVRS',18,'SVRS, Bangladesh Bureau of Statistics, Statistics and Informatics Division, Ministry of Planning',''),
(45,192,'HSD->DGHS->NASP',27,'NASP, Directorate General of Health Services (DGHS), Health Services Division, Ministry of Health & Family Welfare',''),
(46,194,' SID->BBS->HMSS',32,'HMSS, Bangladesh Bureau of Statistics, Statistics and Informatics Division, Ministry of Planning',''),
(47,195,'HSD->DGHS->NTP',33,'NTP, Directorate General of Health Services (DGHS), Health Services Division, Ministry of Health & Family Welfare',''),
(48,196,'HSD->DGHS->NMEP',34,'NMEP, Directorate General of Health Services (DGHS), Health Services Division, Ministry of Health & Family Welfare',''),
(49,197,'HSD->DGHS->CDC Unit',35,'CDC, Directorate General of Health Services (DGHS), Health Services Division, Ministry of Health & Family Welfare',''),
(50,199,' SID->BBS->Time Use Survey',60,'TUS, Bangladesh Bureau of Statistics, Statistics and Informatics Division, Ministry of Planning',''),
(51,201,'RTHD->BRTA',161,'Bangladesh Road Transport Authority, Road Transport and Highways Division, Ministry of Road Transport and Bridges',''),
(52,207,' SID->BBS->LAS',59,'LAS, Bangladesh Bureau of Statistics, Statistics and Informatics Division, Ministry of Planning',''),
(53,208,'MoPME->DPE',118,'Ministry of Primary and Mass Education','Need Clarification'),
(54,209,'MoPME->DPE->APSC',106,'APSC, Directorate of Primary Education, Ministry of Primary and Mass Education',''),
(55,210,'MoE->BANBEIS',114,'BES, Bangladesh Bureau of Educational Information and Statistics (BANBEIS), Ministry of Education',''),
(56,212,' SID->BBS-> Access and use of ICT by Household and Individual Survey',174,'Access and Use of ICT by Household and Individual , Bangladesh Bureau of Statistics, Statistics and Informatics Division, Ministry of Planning',''),
(57,214,'MoYS->DYD->MIS',84,'Ministry of Youth and Sports','Need Clarification'),
(58,215,' SID->BBS->EHS',108,'EHS, Bangladesh Bureau of Statistics, Statistics and Informatics Division, Ministry of Planning',''),
(59,218,' SID->BBS->VAW',57,'VAW Survey, Bangladesh Bureau of Statistics, Statistics and Informatics Division, Ministry of Planning',''),
(60,222,' SID->BBS->LFS',63,'QLFS, Bangladesh Bureau of Statistics, Statistics and Informatics Division, Ministry of Planning',''),
(61,223,' SID->BBS->ICT',186,'ICT Use and Access Survey, Bangladesh Bureau of Statistics, Statistics and Informatics Division, Ministry of Planning',''),
(62,224,'PTD->BTRC',93,'Posts and Telecommunications Division, Ministry of Posts, Telecommunications and Information Technology',''),
(63,225,'LGD->DPHE',69,'Public Health Engineering Department, Local Government Division, Ministry of Local Government, Rural Development and Co-operatives',''),
(64,226,'LGD->WASA for City Corporations',66,'WASA for City Corporations, Local Government Division, Ministry of Local Government, Rural Development and Co-operatives',''),
(65,227,'MoEFCC->DoE',67,'Department of Environment, Ministry of Environment, Forest and Climate Change',''),
(66,228,'MoWR->WARPO',68,'Water Resources Planning Organization (WARPO), Ministry of Water Resources',''),
(67,229,'MoWR->WDB',73,'Bangladesh Water Development Board, Ministry of Water Resources',''),
(68,230,'MoA->BMDA',75,'UNSC, Barind Multipurpose Development Authority (BMDA), Ministry of Agriculture',''),
(69,231,'MoWR->JRC',76,'Joint River Commission, Bangladesh, Ministry of Water Resources',''),
(70,232,'PD->SREDA',77,'Sustainable and Renewable Energy Development Authority (SREDA), Power Division, Ministry of Power, Energy and Mineral Resources',''),
(71,234,'EMRD->HCU',78,'Bangladesh Hydrocarbon Unit, Energy and Mineral Resources Division, Ministry of Power, Energy and Mineral Resources',''),
(72,236,'PMO->BIDA',15,'Bangladesh Investment Development Authority (BIDA), Prime Ministerâ€™s Office',''),
(73,240,'MoLE->CLU',46,'Ministry of Labour and Employment',''),
(74,241,'MoLE->DIFE',158,'Department of Inspection for Factory and Establishment, Ministry of Labour and Employment',''),
(75,243,'LGD->LGED',85,'Local Government Engineering Department, Local Government Division, Ministry of Local Government, Rural Development and Co-operatives',''),
(76,244,'MoS->BIWTC',162,'Bangladesh Inland Water Transport Corporation, Ministry of Shipping',''),
(77,245,'MoR->BR',164,'Bangladesh Railway, Ministry of Railways',''),
(78,246,' SID->BBS->SMI',87,'SMI, Bangladesh Bureau of Statistics, Statistics and Informatics Division, Ministry of Planning',''),
(79,249,'MoP->BIDS',91,'Bangladesh Institute of Development Studies, Planning Division, Ministry of Planning',''),
(80,250,'MOFA->UPR',95,'Ministry of Foreign Affairs',''),
(81,252,'MoC->WTO Cell',21,'WTO Cell, Ministry of Commerce',''),
(82,254,'MoCAT->CAAB',165,'Civil Aviation Authority of Bangladesh, Ministry of Civil Aviation and Tourism',''),
(83,256,'MoHPW->Development Authorities, i.e. RAJUK, CDA, KDA etc',131,'Development Authorities (i.e. RAJUK, CDA, KDA, UDD, Ministry of Housing and Public Works',''),
(84,258,'IMED->CPTU',128,'CPTU, Implementation Monitoring & Evaluation Division, Ministry of Planning',''),
(85,264,'MoHA->Department of Prison',137,'Department of Prisons, Security Services Division, Ministry of Home Affairs',''),
(86,268,'IRD->NBR',12,'National Board of Revenue, Internal Resources Division, Ministry of Finance',''),
(87,269,'PMO->NGOAB',25,'NGO Affairs Bureau, Prime Ministerâ€™s Office',''),
(88,270,'PMO->PPPA',29,'Public Private Partnership Office, Prime Ministerâ€™s Office',''),
(89,271,'RTHD->BRTC',161,'Bangladesh Road Transport Authority, Road Transport and Highways Division, Ministry of Road Transport and Bridges',''),
(90,281,'MoF->FD',8,'Finance Division, Ministry of Finance',''),
(91,282,'FAO',190,'FAO',''),
(92,283,' SID->BBS->VAW Survey',57,'VAW Survey, Bangladesh Bureau of Statistics, Statistics and Informatics Division, Ministry of Planning',''),
(93,284,' SID->BBS->Child Labour Survey',181,'Child Labour Survey, Bangladesh Bureau of Statistics, Statistics and Informatics Division, Ministry of Planning',''),
(94,285,'FD',8,'Finance Division, Ministry of Finance',''),
(95,287,' SID->BBS->LAS',59,'LAS, Bangladesh Bureau of Statistics, Statistics and Informatics Division, Ministry of Planning',''),
(96,288,' SID->BBS->QLFS',63,'QLFS, Bangladesh Bureau of Statistics, Statistics and Informatics Division, Ministry of Planning',''),
(97,290,'MoA->BRRI',142,'Bangladesh Agricultural Research Institute (BARI), Ministry of Agriculture',''),
(98,291,'MoA->BJRI',145,'Bangladesh Jute Research Institute (BJRI), Ministry of Agriculture',''),
(99,292,'MoA->CDB',195,'Cotton Development Board, Ministry of Agriculture',''),
(100,294,'MoA->BARC',155,'Bangladesh Agricultural Research Council (BARC), Ministry of Agriculture',''),
(101,297,'DSHE->LASI',102,'LASI, Directorate of Secondary and Higher Education (DSHE), Secondary and Higher Education Division, Ministry of Education',''),
(102,298,'DSHE->NASS',169,'NASS, Directorate of Secondary and Higher Education (DSHE), Secondary and Higher Education Division, Ministry of Education',''),
(103,301,'MoHA->PSD',39,'Bangladesh Police, Public Security Division, Ministry of Home Affairs',''),
(104,302,'MoHA->SSD',129,'Security Services Division, Ministry of Home Affairs',''),
(105,303,'MoHA->SSD->DNC',40,'Department of Narcotics Control, Security Services Division, Ministry of Home Affairs',''),
(106,307,' SID->BBS->GAT Survey',47,'GATS, Bangladesh Bureau of Statistics, Statistics and Informatics Division, Ministry of Planning',''),
(107,310,' SID->BBS->TSA survey',182,'TSA Survey, Statistics and Informatics Division, Ministry of Planning',''),
(108,311,'UNSC',100,'UNSC',''),
(109,314,'FID->BB',13,'Bangladesh Bank, Financial Institutions Division, Ministry of Finance',''),
(110,315,' SID->BBS->Census of Slum Areas and Floating Population',160,'Census wing, Bangladesh Bureau of Statistics, Statistics and Informatics Division, Ministry of Planning',''),
(111,316,'UN-Habitat',109,'UN-Habitat',''),
(112,319,'WTO->OECD',189,'OECD',''),
(113,320,'UNSTATS',152,'UNSTATS, Economic Relations Division, Ministry of Finance',''),
(114,321,'MoE->BANBEIS->BES',114,'BES, Bangladesh Bureau of Educational Information and Statistics (BANBEIS), Ministry of Education',''),
(115,322,'MoE->BANBEIS->BES->SHED',107,'BES, Bangladesh Bureau of Educational Information and Statistics (BANBEIS), Secondary and Higher Education Division, Ministry of Education',''),
(116,334,'FRI',146,'BANGLADESH FISHERIES RESEARCH INSTITUTE (BFRI), Ministry of Fisheries And Livestock',''),
(117,340,' SID->BBS->FIES',9,'FIES, Bangladesh Bureau of Statistics, Statistics and Informatics Division, Ministry of Planning',''),
(118,349,'PovcalNet - The World Bank Group',113,'PovcalNet, WB',''),
(119,361,' SID->BBS->CPHS',94,'CPHS, Bangladesh Bureau of Statistics, Statistics and Informatics Division, Ministry of Planning',''),
(120,362,' SID->BBS->CMNS/MICS',2,'MICS, Bangladesh Bureau of Statistics, Statistics and Informatics Division, Ministry of Planning',''),
(121,372,'MoE->SHED->BANBEIS (BES)',107,'BES, Bangladesh Bureau of Educational Information and Statistics (BANBEIS), Secondary and Higher Education Division, Ministry of Education',''),
(122,381,'NIPSOM->STEP',44,'STEPS, Directorate General of Health Services (DGHS), Health Services Division, Ministry of Health & Family Welfare','Need Clarification'),
(123,384,'MoA->BINA',141,'Bangladesh Institute of Nuclear Agriculture (BINA), Ministry of Agriculture',''),
(124,388,'MoHPW->UDD',131,'Development Authorities (i.e. RAJUK, CDA, KDA, UDD, Ministry of Housing and Public Works','Need Clarification'),
(125,393,'WB->Establishment Survey',140,'WB (Establishment Survey)',''),
(126,394,' SID->SDG Cell',30,'SDG cell, Statistics and Informatics Division, Ministry of Planning',''),
(127,396,' SID->BBS->NAW (Projection)',11,'NAW, Bangladesh Bureau of Statistics, Statistics and Informatics Division, Ministry of Planning',''),
(128,397,'LGD->ORG',149,'Office of the Registrar General, Birth and Death Registration, Local Government Division, Ministry of Local Government, Rural Development and Co-operatives',''),
(129,398,' SID->BBS->ASC',3,'ASC, Bangladesh Bureau of Statistics, Statistics and Informatics Division, Ministry of Planning',''),
(130,399,'HSD->DGHS->IPHN',50,'Health Services Division, Ministry of Health & Family Welfare','Need Clarification'),
(131,401,'BLRI',31,'Bangladesh Livestock Research Institute (BLRI), Ministry of Fisheries And Livestock',''),
(132,402,' SID->BBS->PHC',82,'PHC, Bangladesh Bureau of Statistics, Statistics and Informatics Division, Ministry of Planning',''),
(133,409,'MEFWD->NIPORT->BDHS',41,'BDHS, National Institute of Population Research and Training (NIPORT), Medical Education and Family Welfare Division, Ministry of Health & Family Welfare',''),
(134,419,'NCBT',120,'National Curriculum and Textbook Board (NCTB), Secondary and Higher Education Division, Ministry of Education',''),
(135,420,'MoPME->DPE->NSA',101,'NSA, Directorate of Primary Education, Ministry of Primary and Mass Education',''),
(136,431,'HSD->DGHS->EPI Coverage Evaluation Survey',48,'EPI Coverage Evaluation Survey, Directorate General of Health Services (DGHS), Health Services Division, Ministry of Health & Family Welfare',''),
(137,433,'MoHPW->Development Authorities->RAJUK',131,'Development Authorities (i.e. RAJUK, CDA, KDA, UDD, Ministry of Housing and Public Works','Need Clarification'),
(138,435,'MoHPW->Development Authorities->KDA',131,'Development Authorities (i.e. RAJUK, CDA, KDA, UDD, Ministry of Housing and Public Works','Need Clarification'),
(139,437,' SID->BBS->EPRWMS',125,'EPRWMS, Bangladesh Bureau of Statistics, Statistics and Informatics Division, Ministry of Planning',''),
(140,439,' SID->BBS->ECDS Cell',79,'ECDS Cell, Bangladesh Bureau of Statistics, Statistics and Informatics Division, Ministry of Planning',''),
(141,440,'MoEFCC->BFRI',144,'Bangladesh Forest Research Institute (BFRI), Ministry of Environment, Forest and Climate Change','');
"""